\c roam

INSERT INTO
  posts (title, blog, user_id)
VALUES
  ('The Learners Guild','Lorem ipsum dolor amet food truck authentic butcher selvage. Literally church-key disrupt, succulents pinterest pabst you probably havent heard of them direct trade chambray trust fund helvetica gochujang. IPhone fam raclette pour-over bespoke, readymade offal. Hella neutra pok pok, +1 sartorial everyday carry irony raclette jianbing. Unicorn pop-up street art DIY keffiyeh, blog coloring book hella cray leggings.', '1'),
  ('Homeroom', 'Lorem ipsum dolor amet food truck authentic butcher selvage. Literally church-key disrupt, succulents pinterest pabst you probably havent heard of them direct trade chambray trust fund helvetica gochujang. IPhone fam raclette pour-over bespoke, readymade offal. Hella neutra pok pok, +1 sartorial everyday carry irony raclette jianbing. Unicorn pop-up street art DIY keffiyeh, blog coloring book hella cray leggings.','1'),
  ('Buttercup', 'Lorem ipsum dolor amet food truck authentic butcher selvage. Literally church-key disrupt, succulents pinterest pabst you probably havent heard of them direct trade chambray trust fund helvetica gochujang. IPhone fam raclette pour-over bespoke, readymade offal. Hella neutra pok pok, +1 sartorial everyday carry irony raclette jianbing. Unicorn pop-up street art DIY keffiyeh, blog coloring book hella cray leggings.','1'),
  ('Saigon Bistro', 'Lorem ipsum dolor amet food truck authentic butcher selvage. Literally church-key disrupt, succulents pinterest pabst you probably havent heard of them direct trade chambray trust fund helvetica gochujang. IPhone fam raclette pour-over bespoke, readymade offal. Hella neutra pok pok, +1 sartorial everyday carry irony raclette jianbing. Unicorn pop-up street art DIY keffiyeh, blog coloring book hella cray leggings.','1'),
  ('Moomies Cafe','Lorem ipsum dolor amet food truck authentic butcher selvage. Literally church-key disrupt, succulents pinterest pabst you probably havent heard of them direct trade chambray trust fund helvetica gochujang. IPhone fam raclette pour-over bespoke, readymade offal. Hella neutra pok pok, +1 sartorial everyday carry irony raclette jianbing. Unicorn pop-up street art DIY keffiyeh, blog coloring book hella cray leggings.', '2'),
  ('Charles Blades Barber Spa','Lorem ipsum dolor amet food truck authentic butcher selvage. Literally church-key disrupt, succulents pinterest pabst you probably havent heard of them direct trade chambray trust fund helvetica gochujang. IPhone fam raclette pour-over bespoke, readymade offal. Hella neutra pok pok, +1 sartorial everyday carry irony raclette jianbing. Unicorn pop-up street art DIY keffiyeh, blog coloring book hella cray leggings.','2'),
  ('Bosk', 'Lorem ipsum dolor amet food truck authentic butcher selvage. Literally church-key disrupt, succulents pinterest pabst you probably havent heard of them direct trade chambray trust fund helvetica gochujang. IPhone fam raclette pour-over bespoke, readymade offal. Hella neutra pok pok, +1 sartorial everyday carry irony raclette jianbing. Unicorn pop-up street art DIY keffiyeh, blog coloring book hella cray leggings.', '2'),
  ('Mens Warehouse', 'Lorem ipsum dolor amet food truck authentic butcher selvage. Literally church-key disrupt, succulents pinterest pabst you probably havent heard of them direct trade chambray trust fund helvetica gochujang. IPhone fam raclette pour-over bespoke, readymade offal. Hella neutra pok pok, +1 sartorial everyday carry irony raclette jianbing. Unicorn pop-up street art DIY keffiyeh, blog coloring book hella cray leggings.', '2'),
  (' Organic Bliss', 'Vaporware XOXO venmo, semiotics hot chicken crucifix raclette pok pok. Pour-over four loko lyft vape 3 wolf moon williamsburg venmo cloud bread glossier, poke forage trust fund. Edison bulb chambray cronut artisan asymmetrical yr austin flexitarian prism heirloom whatever raw denim. Meggings vaporware bicycle rights DIY vexillologist gentrify trust fund bitters church-key waistcoat jean shorts. Biodiesel dreamcatcher pabst tousled, gochujang synth tattooed typewriter craft beer paleo wayfarers keytar williamsburg. Occupy mumblecore sartorial kitsch VHS actually vape scenester pug venmo. Pickled viral edison bulb yuccie brunch next level craft beer kombucha knausgaard.', '3'),
  (' Le Soleil Day Spa', 'Vaporware XOXO venmo, semiotics hot chicken crucifix raclette pok pok. Pour-over four loko lyft vape 3 wolf moon williamsburg venmo cloud bread glossier, poke forage trust fund. Edison bulb chambray cronut artisan asymmetrical yr austin flexitarian prism heirloom whatever raw denim. Meggings vaporware bicycle rights DIY vexillologist gentrify trust fund bitters church-key waistcoat jean shorts. Biodiesel dreamcatcher pabst tousled, gochujang synth tattooed typewriter craft beer paleo wayfarers keytar williamsburg. Occupy mumblecore sartorial kitsch VHS actually vape scenester pug venmo. Pickled viral edison bulb yuccie brunch next level craft beer kombucha knausgaard.', '3'),
  ('Hella Fitzgerald', 'Taiyaki hexagon pabst cray banh mi, normcore shaman viral. Flexitarian pickled drinking vinegar viral celiac meditation brunch wayfarers vegan cred kale chips chicharrones venmo. Knausgaard coloring book la croix gochujang brooklyn portland, biodiesel hoodie neutra tbh chia roof party kickstarter. Trust fund cloud bread marfa pork belly, vinyl dreamcatcher sriracha microdosing austin blog chillwave narwhal single-origin coffee hashtag wolf.', '3'),
  ('SomaR Bar and Lounge','Blog vexillologist street art, distillery raw denim seitan leggings kombucha yr taiyaki affogato VHS shoreditch four loko helvetica. Copper mug heirloom schlitz post-ironic bespoke cardigan bicycle rights, tumblr fam raclette readymade gastropub sustainable next level. Bushwick franzen keffiyeh air plant forage, deep v unicorn jean shorts pinterest roof party gastropub. Vexillologist man braid mlkshk hashtag. Vexillologist iceland drinking vinegar meggings normcore unicorn semiotics jianbing godard YOLO small batch vice venmo. Chia DIY distillery photo booth. Twee cliche paleo, pickled pitchfork yr roof party meditation. Authentic tumeric intelligentsia lumbersexual vinyl coloring book retro fixie fanny pack tofu. Health goth cray blue bottle, quinoa plaid tumblr cred 8-bit polaroid roof party selvage.','3');
