INSERT INTO
  cities (name)
VALUES
('Alameda'),
('El Cerrito'),
('Mountain View'),
('San Leandro'),
('Albany'),
('Emeryville'),
('Napa'),
('San Mateo'),
('American Canyon'),
('Fairfax'),
('Newark'),
('San Pablo'),
('Antioch'),
('Fairfield'),
('Novato'),
('San Rafael'),
('Atherton'),
('Foster'),
('City'),
('Oakland'),
('San Ramon'),
('Belmont'),
('Fremont'),
('Oakley'),
('Santa Clara'),
('Belvedere'),
('Gilroy'),
('Orinda'),
('Santa Rosa'),
('Benicia'),
('Half Moon Bay'),
('Pacifica'),
('Saratoga'),
('Berkeley'),
('Hayward'),
('Palo Alto'),
('Sausalito'),
('Brentwood'),
('Healdsburg'),
('Petaluma'),
('Sebastopol'),
('Brisbane'),
('Hercules'),
('Piedmont'),
('Sonoma'),
('Burlingame'),
('Hillsborough'),
('Pinole'),
('South San Francisco'),
('Calistoga'),
('Lafayette'),
('Pittsburg'),
('St. Helena'),
('Campbell'),
('Larkspur'),
('Pleasant Hill'),
('Suisun City'),
('Clayton'),
('Livermore'),
('Pleasanton'),
('Sunnyvale'),
('Cloverdale'),
('Los Altos'),
('Portola Valley'),
('Tiburon'),
('Colma'),
('Los Altos Hills'),
('Redwood City'),
('Union City'),
('Concord'),
('Los Gatos'),
('Richmond'),
('Vacaville'),
('Corte Madera'),
('Martinez'),
('Rio Vista'),
('Vallejo'),
('Cotati'),
('Menlo Park'),
('Rohnert Park'),
('Walnut Creek'),
('Cupertino'),
('Mill Valley'),
('Ross'),
('Windsor'),
('Daly City'),
('Millbrae'),
('San Anselmo'),
('Woodside'),
('Danville'),
('Milpitas'),
('San Bruno'),
('Yountville'),
('Dixon'),
('Monte Sereno'),
('San Carlos'), 
('Dublin'),
('Moraga'),
('San Francisco'), 
('East Palo Alto'),
('Morgan Hill'),
('San Jose')
